on: push
name: Test Workflow
jobs:
  installDependencies:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: npm install yarn --global
      - name: Yarn install
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: yarn
      - name: Test Code
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        run: yarn test
